# Generated by Django 2.1.7 on 2019-03-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=9)),
                ('mobile', models.CharField(max_length=9)),
                ('fax', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=60)),
                ('website', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PartyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
